#!/bin/env ruby

require 'pathname'

ENTRY_DIR = Pathname.pwd
ROOT      = Pathname.new File.expand_path(File.dirname(File.realpath(__FILE__)))
Dir.chdir ROOT

require 'bundler'
Bundler.setup

require 'argument_parser'

DIR = {
	entry:  ENTRY_DIR,
	src:    ROOT.join('src'),
	toc:    ROOT.join('src/TableOfContentsGenerator'),
	readme: ROOT.join('README.md')
}

require DIR[:src].join 'extensions'
require DIR[:src].join 'handle_arguments'
require DIR[:toc].join 'Header'
require DIR[:toc].join 'Generator'
require DIR[:toc].join 'Main'

TOC_MAIN = TableOfContentsGenerator::Main.new
TOC_MAIN.start
