#!/bin/env ruby

require 'pathname'

ENTRY_DIR = Pathname.pwd
ROOT      = Pathname.new File.expand_path(File.dirname(File.realpath(__FILE__)))
Dir.chdir ROOT

require 'bundler'
Bundler.setup

require 'argument_parser'

require 'awesome_print'
require 'byebug'

DIR = {
	entry:  ENTRY_DIR,
	src:    ROOT.join('src'),
	readme: ROOT.join('README.md')
}

require DIR[:src].join 'extensions'
require DIR[:src].join 'handle_arguments'
require DIR[:src].join 'TOCGenerator'
require DIR[:src].join 'TOCHeader'
require DIR[:src].join 'TOCMain'

TOC_MAIN = TableOfContentsGenerator::Main.new
TOC_MAIN.start
